I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    show FogpartS with slowopen
TypeError: Fade() takes at least 3 arguments (5 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script
    show FogpartS with slowopen
  File "C:\Users\Morgan\Downloads\renpy-6.99.4-sdk\renpy\ast.py", line 1236, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\Morgan\Downloads\renpy-6.99.4-sdk\renpy\exports.py", line 1251, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Morgan\Downloads\renpy-6.99.4-sdk\renpy\display\core.py", line 1857, in do_with
    clear=clear)
  File "C:\Users\Morgan\Downloads\renpy-6.99.4-sdk\renpy\display\core.py", line 2276, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "C:\Users\Morgan\Downloads\renpy-6.99.4-sdk\renpy\display\core.py", line 2486, in interact_core
    new_widget=layers_root)
  File "C:\Users\Morgan\Downloads\renpy-6.99.4-sdk\renpy\curry.py", line 38, in __call__
    **dict(self.kwargs.items() + kwargs.items()))
TypeError: Fade() takes at least 3 arguments (5 given)

Windows-7-6.1.7601-SP1
Ren'Py 6.99.4.467
Mushrooms 0.01
